---
server:
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: testuser
    password: testpass

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akshaythakre/spring-cloudconfig-tolls
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/akshaythakre/spring-cloudconfig-tolls-perf
              search-paths:
                - 'station*'
#          username: uname
#          password: pass

